apiVersion: v1
kind: Service
metadata:
  name: shipping-service
  labels:
    app: shipping-service
spec:
  ports:
  - port: 9080
    name: http
  selector:
    app: shipping-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shipping-service-v1
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: shipping-service
        version: v1
    spec:
      containers:
      - name: shipping-service
        image: 955065381857.dkr.ecr.cn-north-1.amazonaws.com.cn/shipping-service:0.2.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_user
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db_pass
      imagePullSecrets:
        - name: new-secret
