pipeline {
    agent any

    stages {
        stage([$class: 'WsCleanup'])

        stage('Checkout') {
            git url: 'https://github.com/DDD-China/shipping-service.git', branch: 'master'
        }
        stage('Test') {
            steps {
                sh './gradlew test'
            }
        }
        stage('Build') {
            steps {
                sh './gradlew build'
            }
        }
        stage('Gen Image') {
            steps {
                sh './ci/genImage.sh'
            }
        }
        stage('Deploy') {
            steps {
                sh './ci/deploy.sh'
            }
        }
    }
}