node{
    step([$class: 'WsCleanup'])

    stage('Checkout') {
        git url: 'https://github.com/DDD-China/shipping-service.git', branch: 'master'
    }

    stage('Test') {
        sh './gradlew test'
    }

    stage('Build') {
        sh './gradlew build'
    }

    stage('GenImage') {
        sh './ci/genImage.sh'
    }

    stage('Deploy') {
        withCredentials([[$class: 'FileBinding', credentialsId: 'kube_config', variable: 'KUBECTL_CONFIG_FILE']]) {
            sh './ci/deploy.sh'
        }

    }
}